#
# (C) Copyright 2023 Rockchip Electronics Co., Ltd
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y += rk3576.o
obj-$(CONFIG_$(PHASE_)CLK) += clk_rk3576.o
obj-$(CONFIG_$(PHASE_)SYSCON) += syscon_rk3576.o
