#
# (C) Copyright 2021 Rockchip Electronics Co., Ltd
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y += rk3568.o
obj-$(CONFIG_$(PHASE_)CLK) += clk_rk3568.o
obj-$(CONFIG_$(PHASE_)SYSCON) += syscon_rk3568.o
